name: Sphinx builds cleanly

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx sphinx-autobuild
    - name: Checking that Sphinx builds cleanly.
      run: |
        sphinx-build -b html -d build/doctrees -W --keep-going -n source build/html
